apiVersion: apps/v1
kind: Deployment
metadata:
  name: shapes
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: shapes
  template:
    metadata:
      labels:
        name: shapes
    spec:
      containers:
      - name: shapes
        image: <OCIIMAGE>
        envFrom:
        - secretRef:
            name: github-secrets
        env:
        - name: DESIGNER_URL
          value: "https://<DOMAIN>/designer"
        - name: DATA_DIR
          value: "/app/data/"
        - name: GITHUB_REPO
          value: shapes
        - name: GITHUB_ORG
          value: thindexed
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: "2"
            memory: 1Gi
